FROM apache/spark:3.5.0

USER root

# Install Python dependencies needed for the fraud detection script
RUN pip install --no-cache-dir \
    numpy==1.24.4 \
    pandas==2.0.3 \
    joblib \
    scikit-learn==1.3.2 \
    pyarrow==12.0.1

USER spark

WORKDIR /opt/spark
